### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by wenzhoulyu** [LinghengMeng/LSTM-TD3#1] opened 2022-02-24 14:27 UTC
when I used the code, an error occurred in ReplayBuffer.
```
in sample_batch_with_history
    hist_obs[i] = self.obs_buf[hist_start_id:id]
ValueError: could not broadcast input array from shape (3,2) into shape (5,2)
```

**Comment by theohh0** [comment] 2023-02-12 21:58
Bit of a long shot but did you ever manage to fix this issue? I'm having the exact same problem...

**Comment by LinghengMeng** [comment] 2023-02-14 04:12
the problem is caused by the actual history length is less than the specified maximum history length when the sampled experience id is at the first few experiences of an episode. This can be solved simply by changing it to `hist_obs[i, :hist_seg_len, :] = self.obs_buf[hist_start_id:id]`. The bug is fixed now. Thanks for the feedback.

**Closed as completed** 2023-02-14 04:12 UTC
